$(document).ready(function(){
                $("#page_home").load("pages/home.html");
                $("#page_pubblication").load("pages/publications.html");
                $("#page_projects").load("pages/projects.html");
                $("#page_research_interest").load("pages/research_interest.html");
                $("#page_awards").load("pages/awards.html");
                $("#page_professional_services").load("pages/professional_services.html");
                
                $("#home").click(function(){
                    $("#page_pubblication").hide();
                    $("#page_projects").hide();
                    $("#page_research_interest").hide();
                    $("#page_awards").hide();
                    $("#page_professional_services").hide();
                    $("#page_home").show();
                });
                $("#publications").click(function(){
                    $("#page_home").hide();
                    $("#page_projects").hide();
                    $("#page_research_interest").hide();
                    $("#page_awards").hide();
                    $("#page_professional_services").hide();
                    $("#page_pubblication").show();
                });
                $("#projects").click(function(){
                    $("#page_home").hide();
                    $("#page_pubblication").hide();
                    $("#page_research_interest").hide();
                    $("#page_awards").hide();
                    $("#page_professional_services").hide();
                    $("#page_projects").show();
                });
                $("#research_interest").click(function(){
                    $("#page_home").hide();
                    $("#page_pubblication").hide();
                    $("#page_projects").hide();
                    $("#page_awards").hide();
                    $("#page_professional_services").hide();
                    $("#page_research_interest").show();              
                });
                $("#awards").click(function(){
                    $("#page_home").hide();
                    $("#page_pubblication").hide();
                    $("#page_projects").hide();
                    $("#page_research_interest").hide(); 
                    $("#page_professional_services").hide();
                    $("#page_awards").show();                               
                });
                $("#professional_services").click(function(){
                    $("#page_home").hide();
                    $("#page_pubblication").hide();
                    $("#page_projects").hide();
                    $("#page_research_interest").hide(); 
                    $("#page_awards").hide();
                    $("#page_professional_services").show();
                });
            });
